# Generated by Django 3.2.5 on 2021-07-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuarioapi',
            name='escola',
            field=models.ManyToManyField(to='app_teste.Escola'),
        ),
    ]
